# BoxDesign AI — Design Model
from sqlalchemy import Column, String, DateTime, Boolean, JSON, Integer, ForeignKey, Enum
from sqlalchemy.orm import relationship
from models.user import Base
from datetime import datetime
import uuid
import enum

class DesignStatus(str, enum.Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETE = "complete"
    FAILED = "failed"

class DesignRequest(Base):
    """
    Stores the initial request from the user for a new box design.
    """
    __tablename__ = "design_requests"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    job_id = Column(String, unique=True, index=True)
    status = Column(Enum(DesignStatus), default=DesignStatus.QUEUED)
    
    # Dimensions
    box_style = Column(String(50), default="RSC")
    length_mm = Column(Integer, nullable=False)
    width_mm = Column(Integer, nullable=False)
    height_mm = Column(Integer, nullable=False)
    unit = Column(String(10), default="mm")
    
    # Logistics/Business context
    box_quantity = Column(Integer, nullable=True)
    weight_kg = Column(String(20), nullable=True)
    photo_urls = Column(JSON, nullable=True) # References to user uploaded product photos
    
    # Creative Brief
    brand_name = Column(String(255))
    product_name = Column(String(255))
    tagline = Column(String(500), nullable=True)
    category = Column(String(100), nullable=True)
    target_market = Column(String(255), nullable=True)
    font_style = Column(String(100), nullable=True)
    preferred_colours = Column(JSON, nullable=True)
    prompt = Column(String(2000), nullable=True)
    use_web_research = Column(Boolean, default=False)
    barcode_number = Column(String(50), nullable=True)
    
    # Metadata
    regenerations_used = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = relationship("User", backref="design_requests")
    generated_designs = relationship("GeneratedDesign", back_populates="request")

class GeneratedDesign(Base):
    """
    Stores the actual designs generated by the AI based on a DesignRequest.
    """
    __tablename__ = "generated_designs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    request_id = Column(String, ForeignKey("design_requests.id"), nullable=False)
    
    theme = Column(String(100), nullable=True)
    thumbnail_url = Column(String(500), nullable=True)
    flat_design_url = Column(String(500), nullable=True) # Path to SVG/CDR
    model_3d_url = Column(String(500), nullable=True)   # Path to GLB/USDZ
    
    colour_palette = Column(JSON, nullable=True)
    fonts = Column(JSON, nullable=True)
    
    is_selected = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    request = relationship("DesignRequest", back_populates="generated_designs")
